FROM --platform=linux/amd64 ubuntu:20.04 

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y wget tar git gzip unzip make cmake software-properties-common curl automake autoconf pkg-config libtool

ADD . /repo
WORKDIR /repo
RUN ./autogen.sh
RUN ./configure
RUN make -j8
RUN make install

ENV LD_LIBRARY_PATH=/usr/local/lib
RUN ldconfig
